

# This is a basic workflow to help you get started with Actions

name: final

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Nightlybuild:
    #if: github.event_name == 'schedule'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2



        

      # Runs a set of commands using the runners shell
      - name: Get Time passed since last commit
        run: |
          TimePassed=$(for branch in `git branch -r | grep -v HEAD`;do echo -e `git show --format="%ar" $branch | head -n 1` \\t$branch; done | sort -r)
          echo $TimePassed
          if [[ $TimePassed == *"seconds"* ]]; then
          echo "It's there!"
          fi
          git show --format="%ar" $branch | head -n 1
          
      - name: Checking if the last commit was more than 24 hrs
        id: check
        run: |
          TimePassed=$(for branch in `git branch -r | grep -v HEAD`;do echo -e `git show --format="%ar" $branch | head -n 1` \\t$branch; done | sort -r)
          echo $TimePassed
          if [[ $TimePassed == *"hours"* ]] || [[ "$TimePassed" == *"minutes"* ]] || [[ $TimePassed == *"seconds"* ]]; then
          echo "It's there!"
          buildRequired=true
          fi
          git show --format="%ar" $branch | head -n 1
          echo ::set-output name=key::$buildRequired
      
      - name: Execute if time passed
        if: steps.check.outputs.key == 'true'
        run: |
          echo hi           
