
# This is a basic workflow to help you get started with Actions

name: final

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Checking if the last commit was more than 24 hrs
      id: check
      run: |
        value=2
        echo ::set-output name=key::$value
      
    - name: b
      if: steps.check.outputs.key == '2'
      run: |
        echo hi
